### ISSUE TITLE
Reimport data

### ISSUE THREAD

**Issue by goranefbl** [Webcreations907/WBC-Importer-extension#1]
Like i said before, great job. 

One note, if user uploaded demo data, deleted it or edited it and want to reupload again, is it possible to do so ? If not ,maybe some button that would say, Enable reimport of uploaded data, that would delete option field. I suppose.

**Comment by FrankM1** [comment]
Another way is to reset the option field if all theme options are reset.

**Comment by Webcreations907** [comment]
Thanks,
Will get a 'Re-Import' button added to it. 

If you're testing it, there is a line commented out, just uncomment it and it will delete the stored values so that you can keep re-importing.
[Link To Line Here](https://github.com/Webcreations907/WBC-Importer-extension/blob/master/wbc_importer/extension_wbc_importer.php#L68)

Only thing about adding it to the reset options, is that users might think that it will delete all the installed content that was imported.

I would just point them to https://wordpress.org/plugins/wordpress-reset/ plugin which will return their install back to default if they wanted to start over.

**Comment by Webcreations907** [comment]
@goranefbl , @FrankM1 
Give that a try, should show a 'Re-Import' button when mousing over a already imported demo. 

:smile:
