### ISSUE TITLE
How are the demo imports sorted?

### ISSUE THREAD

**Issue by MargieinAZ** [Webcreations907/WBC-Importer-extension#14]
I have a large import file, and I've broken it up into several parts. I wan them to display in the Demo Importer panel in proper order. For example, left to right: Part 1, Part 2, Part 3

But mine are displayed in a jumbled order. I've tried renaming them, and it doesn't seem to work.
Any suggestions on how to control the order in which they appear?

Thanks! Awesome extension.
:)

**Comment by genethic** [comment]
I am also interested in a way to sort the demos are displayed

**Comment by Webcreations907** [comment]
Hello,

You can set the demos in order like demo1, demo2, demo3, etc. it list in alpha/num order.

Then use the filter for the title if you want to change the names. 
https://github.com/Webcreations907/WBC-Importer-extension/blob/master/example-functions.php#L59-L75

Once in order though, make sure not to change the order because if you do then say your user imports demo2 and later you call a different demo demo2 then it will look they they already imported it.

There is another way to filter the array of demos (I believe I added that), so let me check that out and see if I can get an example of how to do that together.

**Comment by genethic** [comment]
Hi! I have already named the demos like demo1, demo2, demo3... but they are showed demo5, demo4, demo3, demo6, demo7, demo1, demo2

**Comment by Webcreations907** [comment]
@genethic 

Removed orig message, as I delete that branch.

**Comment by genethic** [comment]
It works perfect! Thanks a lot for fixing!

This was really the only issue I found with your extension, it works very well and is very easy to use. I am looking forwar to see this in the master branch.

**Comment by Webcreations907** [comment]
Great, glad that worked out for you, will get that added.

**Comment by Webcreations907** [comment]
Just merged to master, so that should be in there now :smile:
