### ISSUE TITLE
Duplicate menu & slider after re-import

### ISSUE THREAD

**Issue by herususanto** [Webcreations907/WBC-Importer-extension#16]
How to avoid duplicate menu & slider after re-import? Also is there any way to add another json file for import e.g from tinymce plugin setting?

**Comment by Webcreations907** [comment]
Hello,
You can import anything you'd like, just place the file in the demo folder and use the example-functions.php file as a reference on how to load files for the demo that is being imported. The slider example function would be a good starting point for reference.

Duplicate menus, that is something the WordPress importer does, I was going to looking into the actions/filters they have in the importer and see if there is a way to check to avoid duplicate menu items. Just been a bit behind right now.

Duplicate sliders, in the slider example function you could set/check a option(get_option) during import so that it doesn't duplicate it if imported again.
