### ISSUE TITLE
Theme Check Shows Multiple Errors

### ISSUE THREAD

**Issue by mstoic** [Webcreations907/WBC-Importer-extension#40]
Theme check shows many errors because of usage of <strong>fopen</strong> and <strong>file_get_contents </strong> functions. Can you please change them to use the WP_Filesystem

**Comment by Webcreations907** [comment]
Hello,
Most of those are because of the actual WordPress's importer plugin https://wordpress.org/plugins/wordpress-importer/ , so would need them to change to the WP_Filesystem

**Comment by vburlak** [comment]
@Webcreations907 I wonder why WordPress.org team have not moved Importer on WP_Filesystem.
Every time, when ThemeCheck shows warnings on Wordpress Importer - somewhere in the world a kitten starts crying :smiley_cat:

**Comment by Webcreations907** [comment]
@vburlak  
I'm not to sure why they haven't, I didn't want to change it within the importer to make it easy to swap out when they do update it. 

Theme I'm working on I just put Redux and the importer/extensions in a custom plugin since custom post types have to be in there anyways for Themeforest, will make it easier to update as well.

**Comment by vburlak** [comment]
@Webcreations907 you shouldn't change it. I just backed discussion :+1:
