### ISSUE TITLE
Issue with Re-Import data

### ISSUE THREAD

**Issue by bibiangel1989** [Webcreations907/WBC-Importer-extension#51]
Hi,
I am very glad to find this plugin, it really helped me a lot in development issues theme. But i'm having some problems :
1. Import is so good, but when i'm Re-Import, it does not work, and Menu is duplicated.
2. When I import widgets, if timeout lasted more than normal, imports may lead to malfunction. The same thing with the Internet connection delays.

Any solution for this issue ?
Thanks, this great plugin!
p/s: I using WordPress & ReduxFramework latest version.

**Comment by Webcreations907** [comment]
Hello,
1- That is issue caused but the WordPress Importer plugin, hopefully they will get it worked out on one of their updates.

2- Hard to account for all timeouts and internet connection, but as long as you don't have bunch of high res images then should be ok.
In the future It may get updated so that it uploads in parts, but right now I'm just to far behind to be able to work on that at this time.

Any further questions on this, just let me know.

Thanks
