### ISSUE TITLE
Max Mega Menu Import

### ISSUE THREAD

**Issue by BurakParsAydin** [Webcreations907/WBC-Importer-extension#54]
Hello, 

First of all, thank you for this great extension. It saved my time. :+1: 

Here is my issue, i want to import Max mega menu content by json file. Here is it [https://www.maxmegamenu.com]. But i couldn't see appropriate code block in example-function.php. I also imported Revslider, all my content and theme options.

**Comment by Webcreations907** [comment]
Hello,

Sorry for the delay been bit behind. 

You could use the same function/action that you use to import your sliders. I see that's a paid plugin and I don't have that once so unable to test it out. 

Hoping you got this figured out since it's a bit old, let me know if you have any further questions on this.

Thanks :smile:
