### ISSUE TITLE
Will you add delete dummy data button in future?

### ISSUE THREAD

**Issue by geniuspro** [Webcreations907/WBC-Importer-extension#57]
Hello. 
Thanks for the awesome Redux Extension. This extension is very useful and saves my time.
Can you add Delete dummy data button in future development?

**Comment by Webcreations907** [comment]
Hello,
You can recommend [WordPress Rest](https://wordpress.org/plugins/wordpress-reset/) plugin which will reset the WordPress install back to default. 

Not sure on adding a delete button, because I wouldn't know what was being imported and set up as each user would be different.

Going to close this as I'm trying to get caught back up on this issue tracker, but if you have any further questions about it just let me know.

Thanks
