### ISSUE TITLE
Empty demo - does not list demos

### ISSUE THREAD

**Issue by goranefbl** [Webcreations907/WBC-Importer-extension#9]
Hi, i have few clients that are using my theme from themeforest where i implemented demo importer and when i log to their account i see redux panel that comes with my theme, but when i navigate to demos, doesnt show any, just showing that its empty, while on 90% of users all is good. Do you have private email to whom i can send u admin details and ftp so that you can take a look. I fixed problem for them by manualy uploading but would like to have you check the real issue. I think it might be folder permissions, but nothing happens when i change them.

**Comment by Webcreations907** [comment]
Hello,

Do you have skype for instant messaging? Same username on there if you do. [Removed Email] 

:)

**Comment by Webcreations907** [comment]
Just pushed that change and sent you an email.

# 

So others know what the fix was for and the issue causing it will provide info below.

Some servers require FTP info to use WP_Filesystem causing it to not load the demo directory/files, so I added a fallback which should hopefully fix that issue and doesn't require FTP info. 

:smile:

**Comment by Webcreations907** [comment]
@goranefbl This resolve the issue for you?

**Comment by goranefbl** [comment]
Yup, al good. Thanks!
